//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, Serialize, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Commands")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub command: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::shortcut::Entity",
        from = "Column::Id",
        to = "super::shortcut::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Shortcut,
}

impl Related<super::shortcut::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Shortcut.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
